# Generated by Django 4.0.5 on 2022-07-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='parent',
        ),
        migrations.DeleteModel(
            name='TweetLike',
        ),
    ]
