# Generated by Django 4.0.5 on 2022-07-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
